### ISSUE TITLE
LuceneIndex Optimization for ongoing inserts

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#10]
Currently a lucene index has to be completely rebuilt if you want to see newly inserted entries. This is suboptimal for very large collections but not a real problem at the moment as the usecase of 'i have already 100 million docs and want to index my 100 million +1th document and instantly retrieve it' is not very common

**Comment by lucaro** [comment]
Lucene does support the addition to an index, it is even the default behavior. The choice of whether an existing index is supposed to be updated or replaced by a new one is (to the best of my knowledge) not currently available in cottontail however. Maybe it would make sense to add this. Thoughts @ppanopticon ?

**Comment by ppanopticon** [comment]
I see two possible ways here:

Either, we could introduce a more general notion of 'dirty' entries, that is, entries that have been updated or inserted but not yet 'optimized' (for the lack of a better word). This could be tracked via a default column holding a 'dirty' flag. That flag would be set upon inserts and updates. All optimization operations could then only be applied to entries that have that flag set to true (if supported by the index). 

Another approach would be to generate / update index entries directly when inserting and updating. This is a more difficult change due to the way things are currently setup. Moreover, I expect this to cause significant overhead when we apply changes in large batches, especially for indexes that do not allow for incremental changes. This is mainly because we don't have a notion of transactions that encapsulate multiple insert/update operations.

Therefore, I would go with the first variant. Should we at some point add transaction support for insert and update operations, that variant could actually be extended using the very same mechanism.

**Comment by lucaro** [comment]
I agree that adding a mechanism to track the state of index structures would be a good way going forward. Maybe it could be somehow configurable if 'dirty index structures are supposed to be used or ignored during a query?

**Comment by ppanopticon** [comment]
We can have an option for that - sure. However, since this is ultimately a query optimization issue, which is far away from being solved in an optimal way, I'm not sure how well this can be integrated into how queries are currently processed.

**Comment by lucaro** [comment]
Implemented as a first version in 131ba9b2c5a68fe8f5fcc20c3ec850a89b8b144e. I can't say anything to it's performance (or correctness for that matter) though. @silvanheller can you see if it behaves as you would expect it to?

**Comment by silvanheller** [comment]
Not really since the `update` method is never called during inserts in my tests

**Comment by lucaro** [comment]
Hmm, is there already any way to trigger this @ppanopticon ?

**Comment by ppanopticon** [comment]
> Hmm, is there already any way to trigger this @ppanopticon ?

Push!

No, currently these methods are placeholders, which need to be tied into the UPDATE, DELETE and INSERT logic of the entity. This is probably something I'm going to address in the coming months anyway.

**Comment by ppanopticon** [comment]
This has been added on _dev_ (beta). It works as such:

- If the index is capable of processing incremental updates, then these updates will be executed upon INSERT. It is important to note that changes to the Index depend on how the enclosing transaction terminates! Hence upon ROLLBACK the index should be rolled back and upon COMMIT the changes to the index will be committed.

- If the index is not capable of processing incremental update, then the index will be flagged as `dirty`. Currently, this is not taken into consideration during query planning!

Any feedback on this?

**Comment by silvanheller** [comment]
Ideally there is some way to disable incremental updates while inserting large amounts of data

**Comment by ppanopticon** [comment]
> Ideally there is some way to disable incremental updates while inserting large amounts of data

While I see what your intention is, couldn't the same be achieved by simply dropping the index prior to doing that insert and then re-creating it afterwards?

**Comment by silvanheller** [comment]
Sure. Maybe we can close this issue then and open a new one with a feature request for a command to disable incremental updates.
