### ISSUE TITLE
Auto Incrementing Ids

### ISSUE THREAD

**Issue by lucaro** [vitrivr/cottontaildb#134]
If I see this correctly, there is currently no way to have auto incrementing ids for rows in an entity. I would find it tremendously useful to have such a thing. Since this would require a change in the column definition, would it make more sense to have dedicated types like the `SERIAL` type in PostgreSQL or a column property like `AUTO_INCREMENT` such as it is implemented in MySQL?

**Comment by ppanopticon** [comment]
I would argue for a `SERIAL` and a `BIGSERIAL` type (INT and LONG).  Actually, the basic facilities to support this (serials) are already integrated. We only need to add the type and handle them upon insert.

Do you know if SERIAL types in PostgreSQL can be updated, i.e., the value can be changed after the fact?

**Comment by ppanopticon** [comment]
There now is a prototype for this feature on ``feature/serial``. I have updated the DMLServiceTest unit-test to include this feature by adding an auto-increment column. Few remarks:

- I have decided against using dedicated types and instead introduced the ``autoIncrement`` flag for columns (only works for ``Integer`` and ``Long``). The reason for this is that adding new types would have had serious implications across the entire type system.
- Technically, this change is incompatible with existing Cottontail DB instances due to the need to serialize the flag to the catalogue.

Based on this and depending on how urgent this feature request is, I would propose to integrate this into the next major release of Cottontail DB, which should see yet another change to the storage engine.

**Comment by lucaro** [comment]
Hey, great, thanks a lot for the quick reaction. I'll play with this a bit over the next days and provide feedback. I can't comment on the suggested timeline, since I don't know what the target is for the next major release. For my current use case, working from a feature branch is not a problem for the short or medium term.

**Comment by lucaro** [comment]
As a follow-up on this: the functionality that exists on the `serial` branch works quite well. The only issue with the current implementation is that there is no way to get the newly generated id directly from an insert, but it requires a second query. This is rather inefficient, especially when multiple rows need to be inserted into multiple entities that use such serial ids as keys. It would be much nicer if one could request the latest values of the serial fields to be returned from the insert call directly, as this would alleviate the need for additional queries. Since they create quite some overhead, this would also result in a non-negligible speedup.

Also, what is the timeline for this feature branch to be merged?

**Comment by lucaro** [comment]
I built something along those lines in https://github.com/vitrivr/cottontaildb/commit/f3d5d9f1d0dcde0c5620880f43a8e5e582a8530d. It works, but I'm sure there's a way to make it prettier.

**Comment by ppanopticon** [comment]
This is possible with version ``0.16.0``.
