### ISSUE TITLE
Insertion Time Increase

### ISSUE THREAD

**Issue by gabuzi** [vitrivr/cottontaildb#24]
Insertion of roughly 9 million Complex32Vectors of length 20 show an increase in required time of rev. c0eb4e2 (I call it new version here) over a version based on rev. 1696878 (old version).

The new version took about 30 min, while the old version took ca 12 min.

All tests were run on a 13" MacBook Pro from 2015 with 16 GB of RAM and a Core i5-5287U CPU @ 2.9 GHz.

**Comment by ppanopticon** [comment]
Since the way INSERTS are handled has changed drastically on dev, this needs to be re-evaluated there. Should execution time be unacceptable, please re-open another bug. 

It is very likely, though, that the increase in time reported here is not actually a bug but stems from changes / additional checks conducted during processing.
