### ISSUE TITLE
forceUnmapMappedFiles causes Crashes on Unix-Systems

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#7]
setting the `forceUnmapMappedFiles` variable in the config to `true` causes crashes on startup and dropping / creating entities.

This is both on ubuntu and macOS an issue. The easiest way to reproduce the bug is to remove the data directory and launch cottontail via `./gradlew run`

Example stacktrace:

```
Exception in thread "main" java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner;
        at org.mapdb.volume.ByteBufferVol.unmap(ByteBufferVol.java:340)
        at org.mapdb.volume.MappedFileVol.close(MappedFileVol.java:183)
        at org.mapdb.WriteAheadLog.destroyWalFiles(WriteAheadLog.java:792)
        at org.mapdb.StoreWAL.commit(StoreWAL.kt:632)
        at ch.unibas.dmi.dbis.cottontail.database.catalogue.Catalogue.initStore(Catalogue.kt:254)
        at ch.unibas.dmi.dbis.cottontail.database.catalogue.Catalogue.<init>(Catalogue.kt:59)
        at ch.unibas.dmi.dbis.cottontail.CottontailKt.main(Cottontail.kt:33)
```

**Comment by lucaro** [comment]
This appears to be a Java 9+ related issue, see for comparison:

https://github.com/jankotek/mapdb/issues/879
https://github.com/jankotek/mapdb/pull/939

**Comment by ppanopticon** [comment]
Well it is - kind of and I presume the exception reported by Silvan can be attributed to the Java version. However, there also seems to be fundamental issues with certain platforms. 

The underlying problem is, that memory mappings are not unmapped until the respective ByteBuffer is garbage collected, which is something we cannot influence directly. This has been a known JVM issue for several years now. This behaviour has very different implications on different platforms. E.g. on Windows it causes files to remain locked even after a ByteBuffer has been closed. This makes drop operations as implemented by Cottontail DB virtually impossible (as Loris will confirm).

The (MapDB) Cleaner Hack offers a workaround but indeed it breaks on Java 9+, for which there is a slightly different, yet still unofficial way to handle this issue. Solving this problem basically means interfering with the MapDB storage engine on a very low level, which (again) begs the question, whether to fork the library or look for a replacement.

I guess as a workaround we can just refrain from setting this flag on non-windows systems.

**Comment by lucaro** [comment]
The referenced pull request (https://github.com/jankotek/mapdb/pull/939) apparently fixes this issue on the MapDB side of things. There is however no way to know when something like this might make it into the code base...

**Comment by silvanheller** [comment]
I think this is resolved by the config flag.
