### ISSUE TITLE
Use default values when no config is specified

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#90]
It would be easier to deploy cottontail from the release-tarball if no config value would simply result in the default config being taken. In most cases, users will anyway take the default config provided on the repo.

**Comment by ppanopticon** [comment]
This is not possible at the moment because there is no "default config".  While there are default values for most fields, there is the (required) path to the data folder that does not have a default value. 

Furthermore, as with any DBMS, there are values in the config that require fine tuning in an actual setup. So I'm not sure at this point, if not requiring a config-file is a sensible thing to do. But let's assume it was, here are the options I see:

1. We simply assume a data folder (e.g., relative to cottontail). Since Cottontail DB is a multi-platform application, we can't just go for, let's say, /etc/cottontaildb/data 
2. Data folder can / must be provided via program argument

I presume that with a Docker deployment im mind, option 1 is not optimal since in fact the path to the data folder should be specifiable. Which leaves option 2.

But then again, both add some complexity to the startup procedure with very little obvious gain because one may simply provide a default config with the deployment.

**Comment by lucaro** [comment]
I am not aware of any of the 'big' DBMS that would require you to specify the path where it is supposed to store things to disk during setup. For some of them, it's actually not trivial to change where and how they do so. I'd therefore suggest to use `./data` as a reasonable default.

**Comment by ppanopticon** [comment]
> I am not aware of any of the 'big' DBMS that would require you to specify the path where it is supposed to store things to disk during setup. For some of them, it's actually not trivial to change where and how they do so. I'd therefore suggest to use `./data` as a reasonable default.

I was merely referring to the other types of settings and I'm not talking about 'required to' but 'having the ability to' .  But that's beside the point. What I'm questioning here, is the advantage of having an _implicit_ 'default config' (in memory) as opposed to an _explicit_ default config that is stored somewhere physically. 

But I guess we can settle for this: 
- If no config file is specified upon startup, Cottontail DB will resort to `./config.json`. This is already the case!
- **New:** If there is no configuration file exists under the specified path, Cottontail DB will just go ahead and create one.
- **New:** Default value for the data folder would then be `./data`

Would that solve the complications for deployment?

**Comment by sauterl** [comment]
Specifically for Docker usage, I added a little [config lookup logic](https://github.com/vitrivr/cottontaildb/blob/master/src/main/kotlin/org/vitrivr/cottontail/Cottontail.kt#L80) a while ago.

I very much like the two new points @ppanopticon suggested:

> **New**: If there is no configuration file exists under the specified path, Cottontail DB will just go ahead and create one.
> **New**: Default value for the data folder would then be `./data`

**Comment by ppanopticon** [comment]
> Specifically for Docker usage, I added a little [config lookup logic](https://github.com/vitrivr/cottontaildb/blob/master/src/main/kotlin/org/vitrivr/cottontail/Cottontail.kt#L80) a while ago.
> 
> I very much like the two new points @ppanopticon suggested:
> 
> > **New**: If there is no configuration file exists under the specified path, Cottontail DB will just go ahead and create one.
> > **New**: Default value for the data folder would then be `./data`

Indeed! Thanks @sauterl for weighing in. And maybe to clarify:  Cottontail DB's resorting to `./config.json` only happens if all the other options didn't yield a result. Hence, one can actually influence the path to the configuration file via environment variable.

The proposed solution with creating a default config should be fully compatible to all of this.

**Comment by lucaro** [comment]
I would like the functionality of it explicitly creating its config file if none is found. It appears to me as the most intuitive solution.

**Comment by ppanopticon** [comment]
Then this shall be shipped with the next release, if Silvan agrees as well :-)

**Comment by silvanheller** [comment]
Sure, works for me

**Comment by ppanopticon** [comment]
This has been addressed with the `0.14.0` release.
