### ISSUE TITLE
shadowJar not executable

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#93]
On `master`, executing `gradlew shadowJar` results in a jar which cannot be started.

**Comment by Spiess** [comment]
I can confirm, the error message indicates that the manifest may not be generated correctly:
`no main manifest attribute, in build/libs/cottontaildb-0.14.1-all.jar`

**Comment by Spiess** [comment]
After some further thought, I have realized that this behavior is probably intended now that Cottontail DB has moved to a similar subproject structure as Cineast.

To produce the Cottontail DB CLI fat jar, the correct gradle task is `cottontaildb-cli:shadowJar`, for the database I believe it's `cottontaildb-dbms:shadowJar`.

Although this is intended behavior, I think this issue should stay up because the README and documentation have not been updated accordingly.

**Comment by lucaro** [comment]
I agree, this looks more like a documentation issue than an implementation issue to me. Maybe we'd want to prevent the generation of av shadowJar on top-level, as its semantics would not be clear.
